--- Day 6: Probably a Fire Hazard ---
Because your neighbors keep defeating you in the holiday house decorating contest year after year, you've decided to deploy one million lights in a 1000x1000 grid.

Furthermore, because you've been especially nice this year, Santa has mailed you instructions on how to display the ideal lighting configuration.

Lights in your grid are numbered from 0 to 999 in each direction; the lights at each corner are at 0,0, 0,999, 999,999, and 999,0. The instructions include whether to turn on, turn off, or toggle various inclusive ranges given as coordinate pairs. Each coordinate pair represents opposite corners of a rectangle, inclusive; a coordinate pair like 0,0 through 2,2 therefore refers to 9 lights in a 3x3 square. The lights all start turned off.

To defeat your neighbors this year, all you have to do is set up your lights by doing the instructions Santa sent you in order.

For example:

turn on 0,0 through 999,999 would turn on (or leave on) every light.
toggle 0,0 through 999,0 would toggle the first line of 1000 lights, turning off the ones that were on, and turning on the ones that were off.
turn off 499,499 through 500,500 would turn off (or leave off) the middle four lights.
After following the instructions, how many lights are lit?

In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
row = [0 for r in range(10)]
arr = np.array([row for r in range(10)])
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [3]:
row = [0 for r in range(10)]
arr = np.array([row for r in range(10)])

# get start and end point (down,right)
s_point = (2,3)
e_point = (7,6)

# get start and end row and start and end column
s_row = s_point[0]
e_row = e_point[0]

s_col = s_point[1]
e_col = e_point[1]

# get rows and columns effected
rows = [s_row + r for r in range(0, e_row-s_row+1)]
cols = [s_col + r for r in range(0, e_col-s_col+1)]

print(rows, cols)

for row in rows:
    for col in cols:

        arr[row][col] = 1
        

[2, 3, 4, 5, 6, 7] [3, 4, 5, 6]


In [4]:
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
import regex as re

# get 100,000 by 100,000 array

row = [0 for r in range(100_000)]
arr = np.array([row for r in range(100_000)])

strings = [line.strip() for line in open('input2015_6.txt').readlines()]

for string in strings:
    
    command = re.search(r'toggle|off|on',string)
    
    points = re.findall('\d+,\d+', string)
    
    s_point = points[0].split(',')
    
    e_point = points[1].split(',')
    
    # get start and end row and start and end column
    s_row = int(s_point[0])
    e_row = int(e_point[0])

    s_col = int(s_point[1])
    e_col = int(e_point[1])
    
    # get rows and columns effected
    rows = [s_row + r for r in range(0, e_row-s_row+1)]
    cols = [s_col + r for r in range(0, e_col-s_col+1)]
    
    if command == 'off':
        
        for row in rows:
            for column in columns:
            
                arr[row][col] = 0
                
    elif command == 'on':
        
        for row in rows:
            for column in columns:
            
                arr[row][col] = 1
                
    elif command == 'toggle':
        
        for row in rows:
            for column in columns:
            
                if arr[row][col] == 1:
                    
                    arr[row][col] = 0
                    
                if arr[row][col] == 0:
                    
                    arr[row][col] = 1
sum(sum(arr))

In [ ]:
sum([4,4,90])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [5,10,15]])
sum(sum(arr))